/**
 * 存放今天数据，也可简单修改代码后使用 ajax
 */
var data = [
  { type: '未知', value: 654 },
  { type: '17 岁以下', value: 654 },
  { type: '18-24 岁', value: 4400 },
  { type: '25-29 岁', value: 5300 },
  { type: '30-39 岁', value: 6200 },
  { type: '40-49 岁', value: 3300 },
  { type: '50 岁以上', value: 1500 },
];

var groupData = [
  { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
  { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
  { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
  { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
  { name: 'London', 月份: 'May', 月均降雨量: 47 },
  { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
  { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
  { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
  { name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
  { name: 'Berlin', 月份: 'Feb.', 月均降雨量: 23.2 },
  { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
  { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
  { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
  { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
  { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
  { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
];

var pointData = [
  { x: 1, y: 4.181 },
  { x: 2, y: 4.665 },
  { x: 3, y: 5.296 },
  { x: 4, y: 5.365 },
  { x: 5, y: 5.448 },
  { x: 6, y: 5.744 },
  { x: 7, y: 5.653 },
  { x: 8, y: 5.844 },
  { x: 9, y: 6.362 },
  { x: 10, y: 6.38 },
  { x: 11, y: 6.311 },
  { x: 12, y: 6.457 },
  { x: 13, y: 6.479 },
  { x: 14, y: 6.59 },
  { x: 15, y: 6.74 },
  { x: 16, y: 6.58 },
  { x: 17, y: 6.852 },
  { x: 18, y: 6.531 },
  { x: 19, y: 6.682 },
  { x: 20, y: 7.013 },
  { x: 21, y: 6.82 },
  { x: 22, y: 6.647 },
  { x: 23, y: 6.951 },
  { x: 24, y: 7.121 },
  { x: 25, y: 7.143 },
  { x: 26, y: 6.914 },
  { x: 27, y: 6.941 },
  { x: 28, y: 7.226 },
  { x: 29, y: 6.898 },
  { x: 30, y: 7.392 },
  { x: 31, y: 6.938 },
];

// S2
var s2Data = [
  {
    province: '浙江',
    city: '杭州',
    type: '笔',
    price: '1',
  },
  {
    province: '浙江',
    city: '杭州',
    type: '纸张',
    price: '2',
  },
  {
    province: '浙江',
    city: '舟山',
    type: '笔',
    price: '17',
  },
  {
    province: '浙江',
    city: '舟山',
    type: '纸张',
    price: '6',
  },
  {
    province: '吉林',
    city: '丹东',
    type: '笔',
    price: '8',
  },
  {
    province: '吉林',
    city: '白山',
    type: '笔',
    price: '12',
  },
  {
    province: '吉林',
    city: '丹东',
    type: '纸张',
    price: '3',
  },
  {
    province: '吉林',
    city: '白山',
    type: '纸张',
    price: '25',
  },
  {
    province: '浙江',
    city: '杭州',
    type: '笔',
    cost: '0.5',
  },
  {
    province: '浙江',
    city: '杭州',
    type: '纸张',
    cost: '20',
  },
  {
    province: '浙江',
    city: '舟山',
    type: '笔',
    cost: '1.7',
  },
  {
    province: '浙江',
    city: '舟山',
    type: '纸张',
    cost: '0.12',
  },
  {
    province: '吉林',
    city: '丹东',
    type: '笔',
    cost: '10',
  },
  {
    province: '吉林',
    city: '白山',
    type: '笔',
    cost: '9',
  },
  {
    province: '吉林',
    city: '丹东',
    type: '纸张',
    cost: '3',
  },
  {
    province: '吉林',
    city: '白山',
    type: '纸张',
    cost: '1',
  },
];
